### PR TITLE
Add the packaging metadata to build the zcash-mini snap

### PR DESCRIPTION
**Pull request by elopio**
This is a package for the secure installation of apps that works in Ubuntu and other Linux distributions.

### CODE REVIEW

**Comment by elopio** [comment]
Hello!

I've been playing with snaps and zcash for a few weeks, and found your project. I think the security model that we are developing in Ubuntu will be a great fit, and if you publish it to the store you will expose it to a lot more users.

You can find more information about snapcraft here: http://snapcraft.io/

To test it in an Ubuntu 16.04 machine:

    $ sudo apt install git snapcraft
    $ git clone https://github.com/elopio/zcash-mini
    $ cd zcash-mini
    $ git checkout snapcraft
    $ snapcraft
    $ sudo snap install *.snap --dangerous

If you have any questions or comments, please let me know.

**Comment by FiloSottile** [comment]
Thanks!

Does this have to published to the store by me, or can it have a maintainer like packages usually do?

**Comment by elopio** [comment]
Thanks for the review :)

@FiloSottile the idea is that upstream manages the package directly, with no intermediaries.
You can register the snap and maybe push an initial snap to the edge channel at: https://myapps.developer.ubuntu.com/dev/click-apps/register-name/

After that, devs usually hook a CI system like travis or launchpad to make continuous deliveries to the edge channel on every change to the master branch, so everything is automated. I'd be happy to guide you on this if you are interested.

We are working hard to make the process as lightweight as possible, so any feedback from you will be highly appreciated.

**Comment by elopio** [comment]
Hey @FiloSottile, I was wondering if you had a chance to take a look at the store and push the snap.

**Pull request merged**
